### ISSUE TITLE
The search index is not available

### ISSUE THREAD

**Issue by eidng8** [pirix-gh/eledoc#3]
## 🐞 Bug Report
As reported in TypeStrong/typedoc#1247. I've check the default theme is working fine. The search function breaks while using this plugin. Maybe due to `0.10.x` release has changed the search script?

If you need something to check, here's a [repo](https://github.com/eidng8/xml-patch) for you to test with

**Comment by rxliuli** [comment]
The following versions can be used normally after testing

"eledoc": "^0.2.1",
"typedoc": "^0.16.10",
"typescript": "^3.7.2"

This is an example [repo](https://github.com/rxliuli/rx-util)

> Note: There is indeed a problem with the new version of Typedoc

**Comment by eidng8** [comment]
This doesn't work:

```
    "eledoc": "^0.2.1",
    "typedoc": "^0.17.4",
    "typescript": "^3.8.3",
```

Sorry I may have introduced confusion above. Search script has been changed in `typedoc-default-themes` version `0.10.1`.

**Comment by ShadiestGoat** [comment]
Why is this a won't fix?
